#############################################################################
# Makefile for building: Pacman
# Generated by qmake (2.01a) (Qt 4.8.6) on: jue nov 6 00:26:05 2014
# Project:  Pacman.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile Pacman.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -w -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++11 -O2 -w -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -IUtilities -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = element.C \
		sprite.C \
		main.C \
		segment_follower.C \
		game_panel.C \
		game_map.C \
		pacman.C \
		sprite_factory.C \
		ghost.C \
		telegram.C \
		telegram_sender.C \
		Utilities/functions.C \
		Utilities/vector_2D.C \
		Utilities/time_manager.C moc_game_panel.cpp \
		qrc_images.cpp
OBJECTS       = element.o \
		sprite.o \
		main.o \
		segment_follower.o \
		game_panel.o \
		game_map.o \
		pacman.o \
		sprite_factory.o \
		ghost.o \
		telegram.o \
		telegram_sender.o \
		functions.o \
		vector_2D.o \
		time_manager.o \
		moc_game_panel.o \
		qrc_images.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_off.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Pacman.pro
QMAKE_TARGET  = Pacman
DESTDIR       = 
TARGET        = Pacman

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Pacman.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_off.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile Pacman.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_off.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Pacman.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Pacman1.0.0 || $(MKDIR) .tmp/Pacman1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Pacman1.0.0/ && $(COPY_FILE) --parents element.H sprite.H segment_follower.H game_panel.H game_map.H pacman.H image_buffer.H sprite_factory.H ghost.H find_path.H find_path_breadth_first.H telegram.H telegram_listener.H telegram_sender.H Utilities/def.H Utilities/functions.H Utilities/vector_2D.H Utilities/time_manager.H Utilities/singleton.H .tmp/Pacman1.0.0/ && $(COPY_FILE) --parents images.qrc .tmp/Pacman1.0.0/ && $(COPY_FILE) --parents element.C sprite.C main.C segment_follower.C game_panel.C game_map.C pacman.C sprite_factory.C ghost.C telegram.C telegram_sender.C Utilities/functions.C Utilities/vector_2D.C Utilities/time_manager.C .tmp/Pacman1.0.0/ && (cd `dirname .tmp/Pacman1.0.0` && $(TAR) Pacman1.0.0.tar Pacman1.0.0 && $(COMPRESS) Pacman1.0.0.tar) && $(MOVE) `dirname .tmp/Pacman1.0.0`/Pacman1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Pacman1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_game_panel.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_game_panel.cpp
moc_game_panel.cpp: pacman.H \
		game_map.H \
		segment_follower.H \
		sprite.H \
		element.H \
		telegram_sender.H \
		telegram_listener.H \
		telegram.H \
		messages.H \
		ghost.H \
		find_path.H \
		game_panel.H
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) game_panel.H -o moc_game_panel.cpp

compiler_rcc_make_all: qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_images.cpp
qrc_images.cpp: images.qrc \
		Sprites/Pacman/03.png \
		Sprites/Pacman/04.png \
		Sprites/Pacman/05.png \
		Sprites/Pacman/06.png \
		Sprites/Pacman/07.png \
		Sprites/Pacman/08.png \
		Sprites/Pacman/01.png \
		Sprites/Pacman/02.png \
		Sprites/Tux/Green/03.png \
		Sprites/Tux/Green/04.png \
		Sprites/Tux/Green/05.png \
		Sprites/Tux/Green/06.png \
		Sprites/Tux/Green/07.png \
		Sprites/Tux/Green/08.png \
		Sprites/Tux/Green/01.png \
		Sprites/Tux/Green/02.png \
		Sprites/Tux/Red/03.png \
		Sprites/Tux/Red/04.png \
		Sprites/Tux/Red/05.png \
		Sprites/Tux/Red/06.png \
		Sprites/Tux/Red/07.png \
		Sprites/Tux/Red/08.png \
		Sprites/Tux/Red/01.png \
		Sprites/Tux/Red/02.png \
		Sprites/Tux/Blue/03.png \
		Sprites/Tux/Blue/04.png \
		Sprites/Tux/Blue/05.png \
		Sprites/Tux/Blue/06.png \
		Sprites/Tux/Blue/07.png \
		Sprites/Tux/Blue/08.png \
		Sprites/Tux/Blue/01.png \
		Sprites/Tux/Blue/02.png \
		Sprites/Tux/Black/03.png \
		Sprites/Tux/Black/04.png \
		Sprites/Tux/Black/05.png \
		Sprites/Tux/Black/06.png \
		Sprites/Tux/Black/07.png \
		Sprites/Tux/Black/08.png \
		Sprites/Tux/Black/01.png \
		Sprites/Tux/Black/02.png \
		Sprites/Tux/Yellow/03.png \
		Sprites/Tux/Yellow/04.png \
		Sprites/Tux/Yellow/05.png \
		Sprites/Tux/Yellow/06.png \
		Sprites/Tux/Yellow/07.png \
		Sprites/Tux/Yellow/08.png \
		Sprites/Tux/Yellow/01.png \
		Sprites/Tux/Yellow/02.png \
		Sprites/Tux/White/03.png \
		Sprites/Tux/White/04.png \
		Sprites/Tux/White/05.png \
		Sprites/Tux/White/06.png \
		Sprites/Tux/White/07.png \
		Sprites/Tux/White/08.png \
		Sprites/Tux/White/01.png \
		Sprites/Tux/White/02.png
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name images images.qrc -o qrc_images.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

element.o: element.C element.H
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o element.o element.C

sprite.o: sprite.C sprite.H \
		element.H \
		image_buffer.H \
		game_map.H
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sprite.o sprite.C

main.o: main.C game_panel.H \
		pacman.H \
		game_map.H \
		segment_follower.H \
		sprite.H \
		element.H \
		telegram_sender.H \
		telegram_listener.H \
		telegram.H \
		messages.H \
		ghost.H \
		find_path.H
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.C

segment_follower.o: segment_follower.C segment_follower.H \
		sprite.H \
		element.H \
		game_map.H
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o segment_follower.o segment_follower.C

game_panel.o: game_panel.C sprite_factory.H \
		sprite.H \
		element.H \
		game_panel.H \
		pacman.H \
		game_map.H \
		segment_follower.H \
		telegram_sender.H \
		telegram_listener.H \
		telegram.H \
		messages.H \
		ghost.H \
		find_path.H
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o game_panel.o game_panel.C

game_map.o: game_map.C game_map.H \
		telegram_sender.H \
		telegram_listener.H \
		telegram.H \
		messages.H
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o game_map.o game_map.C

pacman.o: pacman.C pacman.H \
		game_map.H \
		segment_follower.H \
		sprite.H \
		element.H \
		telegram_sender.H \
		telegram_listener.H \
		telegram.H \
		messages.H
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pacman.o pacman.C

sprite_factory.o: sprite_factory.C sprite_factory.H \
		sprite.H \
		element.H \
		pacman.H \
		game_map.H \
		segment_follower.H \
		telegram_sender.H \
		telegram_listener.H \
		telegram.H \
		messages.H \
		ghost.H \
		find_path.H \
		find_path_breadth_first.H \
		find_path_depth_first.H
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sprite_factory.o sprite_factory.C

ghost.o: ghost.C ghost.H \
		pacman.H \
		game_map.H \
		segment_follower.H \
		sprite.H \
		element.H \
		telegram_sender.H \
		telegram_listener.H \
		telegram.H \
		messages.H \
		find_path.H
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ghost.o ghost.C

telegram.o: telegram.C telegram.H
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o telegram.o telegram.C

telegram_sender.o: telegram_sender.C telegram_sender.H \
		telegram_listener.H \
		telegram.H \
		messages.H
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o telegram_sender.o telegram_sender.C

functions.o: Utilities/functions.C 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o functions.o Utilities/functions.C

vector_2D.o: Utilities/vector_2D.C 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vector_2D.o Utilities/vector_2D.C

time_manager.o: Utilities/time_manager.C 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o time_manager.o Utilities/time_manager.C

moc_game_panel.o: moc_game_panel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_game_panel.o moc_game_panel.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

